// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WarehouseManagement.Models;

namespace WarehouseManagement.Migrations.Warehouse
{
    [DbContext(typeof(WarehouseContext))]
    partial class WarehouseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WarehouseManagement.WarehouseModels.wCathegory", b =>
                {
                    b.Property<int>("wCathegoryId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("wCathegoryId");

                    b.ToTable("wCathegories");
                });

            modelBuilder.Entity("WarehouseManagement.WarehouseModels.wItems", b =>
                {
                    b.Property<int>("wItemId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<string>("Manufacturer");

                    b.Property<string>("Name");

                    b.Property<double>("Price");

                    b.Property<int>("Quantity");

                    b.Property<int?>("cathegorywCathegoryId");

                    b.HasKey("wItemId");

                    b.HasIndex("cathegorywCathegoryId");

                    b.ToTable("wItems");
                });

            modelBuilder.Entity("WarehouseManagement.WarehouseModels.wItems", b =>
                {
                    b.HasOne("WarehouseManagement.WarehouseModels.wCathegory", "cathegory")
                        .WithMany("items")
                        .HasForeignKey("cathegorywCathegoryId");
                });
#pragma warning restore 612, 618
        }
    }
}
