// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WarehouseManagement.Models;

namespace WarehouseManagement.Migrations.Wholesale
{
    [DbContext(typeof(WholesaleContext))]
    partial class WholesaleContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WarehouseManagement.WholesaleModels.Cathegory", b =>
                {
                    b.Property<int>("CathegoryId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("CathegoryId");

                    b.ToTable("Cathegories");
                });

            modelBuilder.Entity("WarehouseManagement.WholesaleModels.Items", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CathegoryId");

                    b.Property<string>("Description");

                    b.Property<string>("Manufacturer");

                    b.Property<string>("Name");

                    b.Property<double>("Price");

                    b.Property<int>("Quantity");

                    b.HasKey("ItemId");

                    b.HasIndex("CathegoryId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("WarehouseManagement.WholesaleModels.Items", b =>
                {
                    b.HasOne("WarehouseManagement.WholesaleModels.Cathegory", "cathegory")
                        .WithMany("items")
                        .HasForeignKey("CathegoryId");
                });
#pragma warning restore 612, 618
        }
    }
}
